Code/flaskr/models/User.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class User(db.Model): 
    
    id = db.Column(db.Integer, primary_key=True,autoincrement=True)
    
    username = db.Column(db.String(80), unique=True, nullable=False)
    
    email = db.Column(db.String(120), unique=True, nullable=False)

    def __repr__(self):
        
        return self.username
    
    def get_id(self) -> int:
        
        return self.id
    
    def get_username(self) -> str: 
        
        return self.username
    
    def set_username(self,username) -> None:
        
        self.username = username
        
    def get_email(self) -> str: 
        
        return self.email
        
    def set_email(self,email) -> None:
        
        self.email = email
        
    
        
        

Code/flaskr/app.py
from flask import Flask

from flask_login import LoginManager

import os

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))

os.environ['ROOT_DIR'] = ROOT_DIR

from routes.web import web_bp

app = Flask(__name__)

#App routes
app.register_blueprint(web_bp)


#app.config['SECRET_KEY'] = 'tu_clave_secreta'

#app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///app.db'

#app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

#db

# Migración de la base de datos

#migrate = Migrate(app, db)

# Configuración del administrador de inicio de sesión

#login_manager = LoginManager(app)

#login_manager.login_view = 'login'  # Nombre de la función de inicio de sesión

if __name__ == '__main__':
    
    app.run(debug=True)

Code/flaskr/controllers/data_controller.py
from flask import Flask, redirect, url_for, render_template, Blueprint

import os



ROOT_DIR = os.environ.get('ROOT_DIR')

user_controller_path = os.path.join(ROOT_DIR, 'utils', 'main.py')

Code/flaskr/controllers/user_controller.py
from flask import Flask, redirect, url_for, render_template, Blueprint

def index():    
    return render_template('index.html')
def login():
    return render_template('inicioDeSesion.php')
def register():
    return render_template('registrarse.php')
def profile():
    return render_template('profile.html')
def register_response():
    return render_template('register_response.html')
def forgot_password():
    return render_template('forgot_password.html')
def tendencias():
    return render_template('tendencias.html')
def egresados():
    return render_template('egresado.php')
def dashboard():
    return render_template('dashBoard.php')
def comun():
    return render_template('Comun.php')
def sobrenosotros():
    return render_template('sobreNosotros.html')
def logout():
    return render_template('logout.php')
def conexion():
    return render_template('conexion.php')

Code/flaskr/routes/web.py
from flask import Blueprint

import os

ROOT_DIR = os.environ.get('ROOT_DIR')

user_controller_path = os.path.join(ROOT_DIR, 'controllers', 'user_controller.py')
data_controller_path = os.path.join(ROOT_DIR, 'controllers', 'data_controller.py')

from controllers import user_controller as user

from controllers import data_controller as data

web_bp = Blueprint('web', __name__)

# Define las rutas y las funciones de las vistas aquí



@web_bp.route("/main", endpoint="index")
def index_route():
    return user.index()

@web_bp.route("/login", endpoint="login")
def login_route():
    return user.login()

@web_bp.route("/register", endpoint="register")
def register_route():
    return user.register()

@web_bp.route("/profile", endpoint="profile")
def profile_route():
    return user.profile()

@web_bp.route("/register_response", endpoint="register_response")
def register_response_route():
    return user.register_response()

@web_bp.route("/forgot_password", endpoint="forgot_password")
def profile_route():
    return user.forgot_password()

@web_bp.route("/tendencias", endpoint="tendencias")
def profile_route():
    return user.tendencias()

@web_bp.route("/egresados", endpoint="egresados")
def profile_route():
    return user.egresados()

@web_bp.route("/dashboard", endpoint="dashboard")
def profile_route():
    return user.dashboard()

@web_bp.route("/comun", endpoint="comun")
def profile_route():
    return user.comun()

@web_bp.route("/sobrenosotros", endpoint="sobrenosotros")
def profile_route():
    return user.sobrenosotros()

@web_bp.route("/logout", endpoint="logout")
def profile_route():
    return user.logout()

@web_bp.route("/conexion", endpoint="conexion")
def profile_route():
    return user.conexion()

Code/flaskr/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Internal Movility Hub</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="../static/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/assets/css/templatemo.css">
    <link rel="stylesheet" href="../static/assets/css/custom.css">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="../static/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>


<body>
    <!-- Start Top Nav -->
  <!--  <nav class="navbar navbar-expand-lg d-lg-flex justify-content-between align-items-center" id="templatemo_nav_top">
        <div class="container">
            <a class="navbar-brand text-light" href="#">Internal Movility Hub</a>
            <img src="../static/assets/img/Logo_OmegaHackblanco2 (1).png" id="img-nav" alt="Logo pequeño" class="navbar-brand-img">
        </div>
	</nav> --!>
    <!-- Close Top Nav -->

    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light" id="templatemo_main_nav">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <ul class="navbar-nav mr-auto"> <!-- Alinea los elementos a la izquierda -->
                    <li class="nav-item">
                        <a class="navbar-toggler-icon" href="{{ url_for('web.index') }}" id="templatemo_main_nav_text"></a>
                    </li>
                </ul>
		<!--<a class="navbar-brand mx-auto" href="#">--!> <!-- Coloca el logo en el centro -->
		    <!--<img src="../static/assets/img/IMH _Transparent.png" id="img-nav-main" alt="Logo pequeño" class="navbar-brand-img">--!>
		<!--<ul class="navbar-nav ml-auto">--!> <!-- Alinea los elementos a la derecha --!>
                    <!--<li class="nav-item">
                        <a class="nav-link font-weight-bold" href="{{ url_for('web.login') }}" id="templatemo_main_nav_text">Grafica</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="{{ url_for('web.login') }}" id="templatemo_main_nav_text">Lista</a>
			</li>--!>
                </ul>
            </div>
        </div>
    </nav>
    
    <!-- Close Header --!>

    <section>

        {% block content %}
        {% endblock %}
    </section>

    <!-- Start Footer -->
    <!--<footer class="bg-black" id="tempaltemo_footer">
        <div class="container">
            <div class="row">

                <div class="col-md-3 pt-3">

                    <ul class="list-unstyled text-light footer-link-list">

                        <li>
                            <a class="text-decoration-none" >Copyright © 2023 Magneto</a>
                        </li>
                        <li>
                            <a class="text-decoration-none" >Medellin - Colombia</a>
                        </li>
                        <li>
                            <a class="text-decoration-none" >IngSis 2024-1</a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-3 pt-3">
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" >Internal Movility Hub</a></li>
                    </ul>
                </div>

            
            </div>
  
	    </footer> --!>
    <!-- End Footer -->

    <!-- Start Script -->
    <script src="assets/js/jquery-1.11.0.min.js"></script>
    <script src="assets/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="assets/js/bootstrap.bundle.min.js"></script>
    <script src="assets/js/templatemo.js"></script>
    <script src="assets/js/custom.js"></script>
    <!-- End Script -->
</body>

</html>

Code/flaskr/templates/forgot_password.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>IMH/Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="../static/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/assets/css/templatemo.css">
    <link rel="stylesheet" href="../static/assets/css/custom.css">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="../static/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>

<!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light" id="templatemo_main_nav">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <ul class="navbar-nav mr-auto"> <!-- Alinea los elementos a la izquierda -->
                    <li class="nav-item">
                        <a class="navbar-toggler-icon" href="{{ url_for('web.index') }}" id="templatemo_main_nav_text"></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    <!-- Close Header --!>
	
    <div id="login-forms-div" >
	<div id="login-row-div" class="row">
	    <div class="col" id="login-names">
		<h2>Email</h2>
	    </div>
	    <div class="col" id="login-questions">
		<input type="email" class="form-control" id="btn-pink-empty" aria-describedby="emailHelp">
	    </div> 
	</div>
    	<div id="login-row-div" class="row">
	    <div class="col" id="login-names">
		<h2>Password</h2>
	    </div>
	    <div class="col" id="login-questions">
		<input type="email" class="form-control" id="btn-blue-empty" aria-describedby="emailHelp">
	    </div> 
	</div>
	<div id="login-row-div" class="row">
	    <div class="col" id="login-names">
		<h2>Company</h2>
	    </div>
	    <div class="col" id="login-questions">
		<select id="btn-pink-empty" class="form-select">
		    <option >Magneto</option>
		    <option >Magneton't</option>
		</select>
		<!--<input type="email" class="form-control" id="btn-pink-empty" aria-describedby="emailHelp">--!>
	    </div> 
	</div>
	
	<div id="index-login-spaces-div" ></div>
	
	<div>
	    <a href="{{url_for('web.profile')}}" >
		<button type="submit" class="btn btn-primary" id="btn-pink" >Login</button>
	    </a>
	</div>
	
	<div id="index-contact-spaces-div" ></div>
	
	<div>
	    <a href="{{url_for('web.register')}}" >
		<button type="button" class="btn btn-primary" id="btn-gray" >Forgot Password?</button>
	    </a>
	</div>
	<div id="register-spaces-div" ></div>
    </div>


</body>

Code/flaskr/templates/forgot_password_response.html
H

Code/flaskr/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Linkeado con hojas de estilos-->
    <link rel="stylesheet" type="text/css" media="screen" href="../static/assets/css/style.css">
    <link rel="stylesheet" type="text/css" media="screen" href="../static/assets/css/main.css">
    <!--titulo de pestaña-->
    <title>OpportunityPlat</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
</head>
<body style="background-color: rgb(2, 13, 31);">
    <!--<main id ="mainIndex">
	<div id="header-placeholder" style="position: relative; z-index: 2;"></div>--!>
    <!--uso de javascript para cargar la barra de navegacion-->
    <!--<script>
        // Carga el encabezado desde header.html en #header-placeholder
        fetch("{{url_for('web.dashboard')}}")
            .then(response => response.text())
            .then(data => {
                document.getElementById('header-placeholder').innerHTML = data;
            });
        
    </script> --!>
<!--<div class="video-conteiner">
    <video autoplay muted loop id="myVideo">
        <source src="../static/assets/videos/pattern_-_121797 (1080p).mp4" type="video/mp4">
      </video>
</div>
<div class="gradient-layer"></div>

<div class="indexHome">
    <h1 class="titulo">TE DAMOS LA FORMULA PARA ESTAR <br> EN EL MERCADO LABORAL</h1>
    <h2 class="titulo2">¡En OpportunityPlat te brindamos soluciones espacializadas <br>para darte la información que necesitas!</h2>
    </div> --!>
    <!--<div class="capa"></div>--!>
<div class="utilidades">
    <h1>OPPORTUNITY PLAT</h1>
    <img src="../static/assets/img/logo.jpeg" alt="Imagen">
    
</div>
<div class="tarjetas">
   
    <div id="dashBoardJefe"><a href="{{url_for('web.dashboard')}}">
        <img src="../static/assets/img/whiteStats.png" alt="Imagen"></a>
        <a href="{{url_for('web.dashboard')}}">
        <h3>DASHBOARD</h3>
    </a>
    
        
    </div>

    <div id="dashBoardEgresado"><a href="{{url_for('web.egresados')}}">
        <img src="../static/assets/img/whiteProfile.png" alt="Imagen"></a>
        <a href="{{url_for('web.egresados')}}">
        <h3>EGRESADO</h3>
    </a>
       
    </div>

    <div id="tendencias"><a href="{{url_for('web.tendencias')}}">
        <img src="../static/assets/img/whitetTendencias.png" alt="Imagen"></a>
        <a href="{{ url_for('web.tendencias') }}">
        <h3>TENDENCIAS</h3>
    </a>
      
    </div>
</div>
</main>
    
</body>
</html>

Code/flaskr/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>IMH/Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="../static/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/assets/css/templatemo.css">
    <link rel="stylesheet" href="../static/assets/css/custom.css">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="../static/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>

<!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light" id="templatemo_main_nav">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <ul class="navbar-nav mr-auto"> <!-- Alinea los elementos a la izquierda -->
                    <li class="nav-item">
                        <a class="navbar-toggler-icon" href="{{ url_for('web.index') }}" id="templatemo_main_nav_text"></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    <!-- Close Header --!>
	
    <div id="login-forms-div" >
	<div id="login-row-div" class="row">
	    <div class="col" id="login-names">
		<h2>Email</h2>
	    </div>
	    <div class="col" id="login-questions">
		<input type="email" class="form-control" id="btn-pink-empty" aria-describedby="emailHelp">
	    </div> 
	</div>
    	<div id="login-row-div" class="row">
	    <div class="col" id="login-names">
		<h2>Password</h2>
	    </div>
	    <div class="col" id="login-questions">
		<input type="email" class="form-control" id="btn-blue-empty" aria-describedby="emailHelp">
	    </div> 
	</div>
	<div id="login-row-div" class="row">
	    <div class="col" id="login-names">
		<h2>Company</h2>
	    </div>
	    <div class="col" id="login-questions">
		<select id="btn-pink-empty" class="form-select">
		    <option >Magneto</option>
		    <option >Magneton't</option>
		</select>
		<!--<input type="email" class="form-control" id="btn-pink-empty" aria-describedby="emailHelp">--!>
	    </div> 
	</div>
	
	<div id="index-login-spaces-div" ></div>
	
	<div>
	    <a href="{{url_for('web.profile')}}" >
		<button type="submit" class="btn btn-primary" id="btn-pink" >Login</button>
	    </a>
	</div>
	
	<div id="index-contact-spaces-div" ></div>
	
	<div>
	    <a href="{{url_for('web.register')}}" >
		<button type="button" class="btn btn-primary" id="btn-gray" >Forgot Password?</button>
	    </a>
	</div>
	<div id="register-spaces-div" ></div>
    </div>


</body>

Code/flaskr/templates/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>IMH/Profile</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="../static/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/assets/css/templatemo.css">
    <link rel="stylesheet" href="../static/assets/css/custom.css">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="../static/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>

<!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light" id="templatemo_main_nav">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <ul class="navbar-nav mr-auto"> <!-- Alinea los elementos a la izquierda -->
                    <li class="nav-item">
                        <a class="navbar-toggler-icon" href="{{ url_for('web.index') }}" id="templatemo_main_nav_text"></a>
                    </li> 
                </ul>
            </div>
        </div>
    </nav>
    
    <!-- Close Header --!>
   
    <div id="profile-welcome-div">
	<div id="profile-container">
	    <div id="profile-welcome-icon">
		<h1 id="profile-welcome-icon" class="md-3 bg-3">$You</h1>
	    </div>
	    <div id="profile-welcome-welcome">
		<h1 id="profile-welcome-welcome" class="md-3 bg-3">Welcome!</h1>
	    </div>
	</div>    
    </div>

    <div id="profile-container-cards">
	<div class="container text-center">
	    <div class="row">
		<div class="col">
		    <div class="card" id="profile-div-card">
			<img src="../static/assets/img/Eclipse.png" class="card-img-top" id="profile-image-card">
			<div  id="profile-body-card">
			    <h5 id="profile-title-card">Modelación Númerica</h5>
			    <h5 id="profile-place-card">Medellin,Colombia</h5>
			    <h5 id="profile-company-card">Magneto</h5>
			    <p class="card-text" id="profile-text-card">Se busca encontrar modelos de computación matematica que permitan llegar a interpretar imagenes de tipo DICOM.</p>
			    <div>
				<a href="#" class="btn btn-primary" id="profile-btn-blue-empty">Me Interesa</a>
			    </div>
			</div>
		    </div>
		</div>
		<div class="col">
		    <div class="card" id="profile-div-card">
			<img src="../static/assets/img/IMH_platform.png" class="card-img-top" id="profile-image-card">
			<div class="card-body">
			    <h5 id="profile-title-card">Sistema Postulación Proyectos Interno</h5>
			    <h5 id="profile-place-card">Medellin,Colombia</h5>
			    <h5 id="profile-company-card">Magneto</h5>
			    <p class="card-text" id="profile-text-card">El proyecto tiene el proposito de crear un MPV sobre un Sistema que permita la oferta y postulación de proyectos dentro de la empresa.</p>
			    <div>
				<a href="#" class="btn btn-primary" id="profile-btn-blue-empty">Me Interesa</a>
			    </div>
			</div>
		    </div>
		</div>
		<div class="col">
		    <div class="card" id="profile-div-card">
			<img src="../static/assets/img/download.jpeg" class="card-img-top" id="profile-image-card">
			<div class="card-body">
			    <h5 id="profile-title-card">Software Seguimiento a Procesos</h5>
			    <h5 id="profile-place-card">Medellin,Colombia</h5>
			    <h5 id="profile-company-card">Magneto</h5>
			    <p class="card-text" id="profile-text-card">Con el ideal de agilizar algunos procesos, se ha planteado desarrollar un sistema de software que permita su seguimiento en diferentes situaciones.</p>
			    <div>
				<a href="#" class="btn btn-primary" id="profile-btn-blue-empty">Me Interesa</a>
			    </div>
			</div>
		    </div>
		</div>
	    </div>
	</div>	
    </div>
    
    <div id="profile-spaces-div" ></div>




</body>

Code/flaskr/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>IMH/Register</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="../static/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/assets/css/templatemo.css">
    <link rel="stylesheet" href="../static/assets/css/custom.css">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="../static/assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>

<!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light" id="templatemo_main_nav">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <ul class="navbar-nav mr-auto"> <!-- Alinea los elementos a la izquierda -->
                    <li class="nav-item">
                        <a class="navbar-toggler-icon" href="{{ url_for('web.index') }}" id="templatemo_main_nav_text"></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    <!-- Close Header --!>
	
    <div id="register-forms-div" >
	<div id="login-row-div" class="row">
	    <div class="col" id="login-names">
		<h2>Company Name</h2>
	    </div>
	    <div class="col" id="login-questions">
		<input type="email" class="form-control" id="btn-pink-empty" aria-describedby="emailHelp">
	    </div> 
	</div>
    	<div id="login-row-div" class="row">
	    <div class="col" id="login-names">
		<h2>Business Name</h2>
	    </div>
	    <div class="col" id="login-questions">
		<input type="email" class="form-control" id="btn-blue-empty" aria-describedby="emailHelp">
	    </div> 
	</div>
	<div id="login-row-div" class="row">
	    <div class="col" id="login-names">
		<h2>Main Email</h2>
	    </div>
	    <div class="col" id="login-questions">
		<input type="email" class="form-control" id="btn-pink-empty" aria-describedby="emailHelp">
	    </div> 
	</div>
	<div id="login-row-div" class="row">
	    <div class="col" id="login-names">
		<h2>Name Person in charge</h2>
	    </div>
	    <div class="col" id="login-questions">
		<input type="email" class="form-control" id="btn-blue-empty" aria-describedby="emailHelp">
	    </div> 
	</div>
    	<div id="login-row-div" class="row">
	    <div class="col" id="login-names">
		<h2>Rol inside the company</h2>
	    </div>
	    <div class="col" id="login-questions">
		<input type="email" class="form-control" id="btn-pink-empty" aria-describedby="emailHelp">
	    </div> 
	</div>
	<div id="login-row-div" class="row">
	    <div class="col" id="login-names">
		<h2>One Time Password</h2>
	    </div>
	    <div class="col" id="login-questions">
		<input type="email" class="form-control" id="btn-blue-empty" aria-describedby="emailHelp">
	    </div> 
	</div>

	<div id="index-login-spaces-div" ></div>
	
	<div>
	    <a href="{{url_for('web.register_response')}}" >
		<button type="submit" class="btn btn-primary" id="btn-blue">Register</button>
	    </a>
	</div>
	
	<div id="index-contact-spaces-div" ></div>
    </div>


</body>